language: node_js
node_js: '12'
os: linux
dist: bionic
addons:
    apt:
        packages:
            # These are required to run webkit
            - libwoff1
            - libopus0
            - libwebp6
            - libwebpdemux2
            - libenchant1c2a
            - libgudev-1.0-0
            - libsecret-1-0
            - libhyphen0
            - libgdk-pixbuf2.0-0
            - libegl1
            - libgles2
            - libevent-2.1-6
            - libnotify4
            - libxslt1.1
            - libvpx5
            # This is required to run chromium
            - libgbm1
            # this is needed for running headful tests
            - xvfb

env:
    global:
        # NPM_TOKEN
        - secure: 'rhbqyV+yqj1bg8yexY2b/m7yQ5mvjuLmfLjHYBS2GZynDFhWieodx4yViEA+DO3YMDtRfyrYrtApyNQ7KOZLC9mKivWPLDRTyXZFpTgzKuvgsCVd+2Uk9gzb94A2piMXHYKGOYyuYcXf/RFhBaX5DWU4f3UZlcAwgHDYCB9ckWHGC+IkK+7jDCvqTVhQmGclSi7DsddZ9cxEALEievU1pafC7n9iIHKS6YTMjXB2eJmCHQXtCvijI5U4XtjSz/87JangDooHn8q4X4KxvuXqWGHXBxDGKtJ/H05IQvOlgI940IjWjPckXRH9wRfj9KAKHkIuMPNnWiJqq2h85zyJMEMx2j5eLtizeoceH/pALLnFX/GEFZWX+mC9mEp/Oj4hsqcrYzJJmGgsBbgNcqes6OnvHwjHGxSrp/U7KdjraL/QzH/MD+97KTUgeO0fPVRCncUA3I956KUs3Ympb//gfsJ52g4r321wQV+oNP/r2YITZhB1qsmQVIhDFMGB5Qsphb7NapeOMge7HGjRIe89L/Ub3eRJo5Z/aHvJTU3lG36pgj/uiOy7Etx6n2HNgInaQLjmbqF5r35b5FeF4Ah0kaAfYs9ujAGHWFcaHZJk5BCj0R8L/1Zpg1U0o8sA4Xih09OaHoG9gLkQR3vVEEKzgN8Uk+suko8gNG9drj2UHTA='
        # GH_TOKEN
        - secure: 'ahdGZXCDehxSQl/MVQhWl4JlP3JlkhFGJZ+7vFD06d0fL8TbGfjwW/B6mdfk8KYcalqXLi9MBPy8qCF5Hn+NM+MNDwc24U+6v4DpDxKhPPVFR9CHgxRDFmxQKxRcuA+S7M6+GeS6keiqCisg3sbqNmls730xFa1ZoVBj+IGlPSXQk1FGS4xpGfO1ckXA/Rcmzux2bWzsSHGVynD5UWWkX3xRBeV3yG8qQ8vMlksq4ckEGu1JKwhTu2TEgJhFRagBzdhZRlYo5L8D5oOCXczZWyQSvJe/sFhX6jE9elt7C/09mlCC4V5PhxieR6jdYi7SxukJrTm/NgO+IwQQM3/6+zNoJkGYW6ZBUoG5lrrAabpKnz5EI+JNjuMAXwS/EVOyYYZ2eL8coWxE/X3AO2z8J50aJsfjSrda6gLjbRuhaNA5eW7PUr7pfQMOd7xWdz3tQdNzvfOeMm3BrQ4xSySLYfYMk70TS7Pr13ckE0L+KQ6XVFY8aF0d3g9o8xno2T97ATK4SYecypswAFYAwBuO6eJbnwkD6Agf2RUj9e3bX/aFHfn8VhtazcF6rtHr+CZC3Gx+YJe6QdEceaYKkKOSG+QyavNYuaG9snxb2AfvlcIU9XH1J7/XBISPx/7DEUx5ao+2Drh0Py8jX89HCxk8lB77A2aHcMYwSd0QEUgjigY='

script:
    - npm run build
    - npm run test

deploy:
    provider: script
    skip_cleanup: true
    script: npm run release --dry-run
    on:
        branch: master
